#
# Makefile for the Cypress touchkey driver
#

#ifneq ($(CONFIG_GPIO_INTERFACE), y)
obj-$(CONFIG_KEYBOARD_CYPRESS_TOUCH) += cypress-touchkey.o issp_driver_routines.o issp_main.o issp_routines.o
#endif
